# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openSong1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSong1.sizePolicy().hasHeightForWidth())
        self.openSong1.setSizePolicy(sizePolicy)
        self.openSong1.setMaximumSize(QtCore.QSize(16777215, 70))
        self.openSong1.setObjectName("openSong1")
        self.horizontalLayout.addWidget(self.openSong1)
        self.openSong2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSong2.sizePolicy().hasHeightForWidth())
        self.openSong2.setSizePolicy(sizePolicy)
        self.openSong2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.openSong2.setObjectName("openSong2")
        self.horizontalLayout.addWidget(self.openSong2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Text1 = QtWidgets.QLabel(self.centralwidget)
        self.Text1.setMinimumSize(QtCore.QSize(0, 30))
        self.Text1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Text1.setText("")
        self.Text1.setAlignment(QtCore.Qt.AlignCenter)
        self.Text1.setWordWrap(True)
        self.Text1.setObjectName("Text1")
        self.horizontalLayout_2.addWidget(self.Text1)
        self.Text2 = QtWidgets.QLabel(self.centralwidget)
        self.Text2.setMinimumSize(QtCore.QSize(0, 30))
        self.Text2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Text2.setText("")
        self.Text2.setAlignment(QtCore.Qt.AlignCenter)
        self.Text2.setWordWrap(True)
        self.Text2.setObjectName("Text2")
        self.horizontalLayout_2.addWidget(self.Text2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.Slider = QtWidgets.QSlider(self.centralwidget)
        self.Slider.setMaximum(100)
        self.Slider.setSliderPosition(50)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider.setTickInterval(10)
        self.Slider.setObjectName("Slider")
        self.gridLayout.addWidget(self.Slider, 2, 0, 1, 1)
        self.Mix = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mix.sizePolicy().hasHeightForWidth())
        self.Mix.setSizePolicy(sizePolicy)
        self.Mix.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Mix.setObjectName("Mix")
        self.gridLayout.addWidget(self.Mix, 3, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.Loadbtns = [self.openSong1, self.openSong2]
        self.Text = [self.Text1,self.Text2]
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Song Recognizer"))
        self.openSong1.setText(_translate("MainWindow", "Song 1"))
        self.openSong2.setText(_translate("MainWindow", "Song 2"))
        self.Mix.setText(_translate("MainWindow", "Mix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

